# Replace the "❯" symbol in the prompt with "λ"
[character]
success_symbol = "[λ](bold green)"

[aws]
disabled = true

[ruby]
detect_variables = []

[docker_context]
disabled = true

[git_status]
stashed = ""

[hg_branch]
disabled = true

[package]
disabled = true

[vagrant]
disabled = true
